-- bill-agent schema, v1
-- Authored by hand (not generated by EF migrations) so it's defensible during the thesis defense.
-- Three tables: bills, payments, email_log.
--
-- Design notes (also captured in DECISIONS.md):
--   * gmail_message_id is the idempotency key. The Gmail API guarantees it's unique
--     and stable per message. We never want to insert the same bill twice if the worker
--     polls Gmail again, so we put a UNIQUE constraint on it everywhere it appears.
--   * email_log captures EVERY processed message (invoice, payment, "other"). It's the
--     audit trail: "did the system see this email? what did the LLM say about it?"
--   * bills.status is intentionally a CHECK constraint, not an ENUM type. ENUM in Postgres
--     is annoying to evolve (ALTER TYPE ADD VALUE blocks); CHECK is just a string.
--   * related_references is JSONB (not TEXT[]) so we can query inside it later
--     (e.g. WHERE related_references @> '"SOME-CODE"' for Agent B's reconciliation fallback).

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()

-- ─────────────────────────────────────────────────────────────────────────────
-- email_log
-- One row per Gmail message we've ever looked at. Idempotency lives here.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE email_log (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gmail_message_id    TEXT NOT NULL UNIQUE,
    subject             TEXT,
    sender              TEXT,           -- "from" is reserved in SQL
    kind                TEXT NOT NULL,  -- "invoice" | "payment_confirmation" | "other"
    raw_extraction      JSONB NOT NULL, -- full BillExtraction record from Agent A, for audit
    processed_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_email_log_processed_at ON email_log (processed_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- bills
-- Invoices we owe (or have paid). One row per invoice the LLM extracted.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE bills (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gmail_message_id     TEXT NOT NULL UNIQUE,  -- idempotency: same email → same bill row
    vendor               TEXT NOT NULL,
    amount               NUMERIC(12, 2) NOT NULL,
    currency             TEXT NOT NULL,         -- ISO 4217 (e.g. "MKD")
    due_date             DATE,
    period               TEXT,                  -- "2025-05" or "May 2025" — LLM-normalized
    reference            TEXT,                  -- primary invoice number
    related_references   JSONB NOT NULL DEFAULT '[]'::JSONB,
    confidence           DOUBLE PRECISION NOT NULL,
    reasoning            TEXT,
    status               TEXT NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'paid', 'needs_review')),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes Agent B will lean on for reconciliation (Day 7):
--   "find pending bills for vendor X around period Y close to amount Z"
CREATE INDEX idx_bills_vendor_period_amount ON bills (vendor, period, amount);
CREATE INDEX idx_bills_status               ON bills (status) WHERE status <> 'paid';
CREATE INDEX idx_bills_due_date             ON bills (due_date);

-- ─────────────────────────────────────────────────────────────────────────────
-- payments
-- Payment-confirmation emails. May or may not match a bill — Agent B figures it out (Day 7).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE payments (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gmail_message_id     TEXT NOT NULL UNIQUE,
    vendor               TEXT,                  -- nullable: bank confirmations sometimes omit it
    amount               NUMERIC(12, 2) NOT NULL,
    currency             TEXT NOT NULL,
    paid_date            DATE,
    reference            TEXT,
    related_references   JSONB NOT NULL DEFAULT '[]'::JSONB,
    confidence           DOUBLE PRECISION NOT NULL,
    reasoning            TEXT,
    matched_bill_id      UUID REFERENCES bills(id) ON DELETE SET NULL,  -- filled by Agent B
    last_notified_outcome TEXT,                  -- de-dup for Day 10 Telegram pushes (Matched/Ambiguous/Unmatched)
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payments_vendor_amount ON payments (vendor, amount);
CREATE INDEX idx_payments_unmatched     ON payments (matched_bill_id) WHERE matched_bill_id IS NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- updated_at trigger for bills (so we can show "last status change" in the sheet/telegram)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bills_touch_updated_at
    BEFORE UPDATE ON bills
    FOR EACH ROW
    EXECUTE FUNCTION touch_updated_at();
